version: 2

workflows:
  version: 2
  default:
    jobs:
      - xcode-10
      - xcode-9
      - xcode-10-cocoapods-integration
      - xcode-9-examples

step-library:
  - &restore-cache
      restore_cache:
        keys:
          - carthage-cache-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
          - carthage-cache-v1- # used if checksum fails

  - &restore-cache-cocoapods
      restore_cache:
        keys:
          - cp-cache-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "VietMapCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock" }}
          - cp-cache-v1

  - &restore-cache-podmaster
      restore_cache:
        keys:
          - podmaster-cache

  - &save-cache
      save_cache:
        key: carthage-cache-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
        paths:
          - Carthage

  - &save-cache-cocoapods
      save_cache:
        key: cp-cache-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "VietMapCoreNavigationTests/CocoaPodsTest/PodInstall/Podfile.lock" }}
        paths:
          - VietMapCoreNavigationTests/CocoaPodsTest/PodInstall/Pods

  - &save-cache-podmaster
      save_cache:
        key: podmaster-cache
        paths:
          - "~/.cocoapods/repos/master"

  - &prepare
      run:
        name: Prepare
        command: |
          git submodule sync
          brew install carthage
          echo "foo" > ~/.mapbox

  - &prepare-iphone6s-plus-ios-11
      run:
        name: Prepare iPhone 6s Plus iOS 11
        command: xcrun instruments -w "iPhone 6s Plus (11.4) [" || true

  - &prepare-iphone6s-plus-ios-12
      run:
        name: Prepare iPhone 6s Plus iOS 12
        command: xcrun instruments -w "iPhone 6s Plus (12.0) [" || true

  - &reset-simulators
      run:
        name: Reset simulators
        command: |
          bundle install
          SNAPSHOT_FORCE_DELETE=1 bundle exec fastlane snapshot reset_simulators

  - &verify-missing-localizable-strings
      run:
        name: Verify missing localizable strings
        command: |
          ./scripts/convert_string_files.sh
          git diff --exit-code -- */*/*.lproj

  - &install-dependencies
      run:
        name: Install Dependencies
        command: carthage bootstrap --platform ios --cache-builds --configuration Release --no-use-binaries

  - &build-test-VietMapCoreNavigation-ios-11
      run:
        name: Build and Test VietMapCoreNavigation
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 6 Plus' -project VietMapNavigation.xcodeproj -scheme VietMapCoreNavigation  -resultBundlePath VietMapCoreNavigationResults clean build test | tee VietMapCoreNavigation-xcodebuild.log | xcpretty

  - &build-test-VietMapCoreNavigation-ios-12
      run:
        name: Build and Test VietMapCoreNavigation
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 6 Plus' -project VietMapNavigation.xcodeproj -scheme VietMapCoreNavigation -resultBundlePath VietMapCoreNavigationResults clean build test | tee VietMapCoreNavigation-xcodebuild.log | xcpretty

  - &build-test-VietMapNavigation-ios-11
      run:
        name: Build and Test VietMapNavigation
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 6 Plus' -project VietMapNavigation.xcodeproj -scheme VietMapNavigation -resultBundlePath VietMapNavigationResults clean build test | tee VietMapNavigation-xcodebuild.log | xcpretty

  - &build-test-VietMapNavigation-ios-12
      run:
        name: Build and Test VietMapNavigation
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 6 Plus' -project VietMapNavigation.xcodeproj -scheme VietMapNavigation -resultBundlePath VietMapNavigationResults clean build test | tee VietMapNavigation-xcodebuild.log | xcpretty

  - &build-Example-Obj-C
      run:
        name: Build Example-Objective-C
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 6 Plus' -project VietMapNavigation.xcodeproj -scheme Example-Objective-C clean build | xcpretty

  - &build-Example-Swift
      run:
        name: Build Example-Swift
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 6 Plus' -project VietMapNavigation.xcodeproj -scheme Example-Swift clean build | xcpretty

  - &cocoapods-integration-test
      run:
        name: CocoaPods integration test
        command: |
          cd VietMapCoreNavigationTests/CocoaPodsTest/PodInstall
          pod install --repo-update
          xcodebuild -workspace PodInstall.xcworkspace/ -scheme PodInstall -destination 'platform=iOS Simulator,name=iPhone 6 Plus' clean build | xcpretty

  - &print-VietMapNavigation-xcodebuild-log
      run:
        name: Print VietMapNavigation-xcodebuild.log
        when: on_fail
        command: cat VietMapNavigation-xcodebuild.log

  - &print-VietMapCoreNavigation-xcodebuild-log
      run:
        name: Print VietMapCoreNavigation-xcodebuild.log
        when: on_fail
        command: cat VietMapCoreNavigation-xcodebuild.log

  - &store-VietMapNavigationResults-artifacts
      store_artifacts:
          path: VietMapNavigationResults

  - &store-VietMapCoreNavigationResults-artifacts
      store_artifacts:
          path: VietMapCoreNavigationResults

jobs:
  xcode-10:
    macos:
      xcode: "10.0.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - *reset-simulators
      - *prepare-iphone6s-plus-ios-12
      - *restore-cache
      - *install-dependencies
      - *build-test-VietMapCoreNavigation-ios-12
      - *build-test-VietMapNavigation-ios-12
      - *print-VietMapNavigation-xcodebuild-log
      - *print-VietMapCoreNavigation-xcodebuild-log
      - *store-VietMapNavigationResults-artifacts
      - *store-VietMapCoreNavigationResults-artifacts
      - *save-cache

  xcode-9:
    macos:
      xcode: "9.4.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - *prepare-iphone6s-plus-ios-11
      - *restore-cache
      - *install-dependencies
      - *verify-missing-localizable-strings
      - *build-test-VietMapCoreNavigation-ios-11
      - *build-test-VietMapNavigation-ios-11
      - *print-VietMapNavigation-xcodebuild-log
      - *print-VietMapCoreNavigation-xcodebuild-log
      - *store-VietMapNavigationResults-artifacts
      - *store-VietMapCoreNavigationResults-artifacts
      - *save-cache

  xcode-10-cocoapods-integration:
    macos:
      xcode: "10.0.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *restore-cache-podmaster
      - *restore-cache-cocoapods
      - *cocoapods-integration-test
      - *save-cache-cocoapods
      - *save-cache-podmaster

  xcode-9-examples:
    macos:
      xcode: "9.4.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - *prepare-iphone6s-plus-ios-11
      - *restore-cache
      - *install-dependencies
      - *build-Example-Obj-C
      - *build-Example-Swift
      - *save-cache
